[project]
name = "casper-cogs"
version = "0.1.0"
description = "casper's brain"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "pendulum>=3.2.0",
]

[dependency-groups]
dev = [
  "red-discordbot>=3.5.24",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "S311",
]
